/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-109600-gb37795688a-20230114"
#endif /* AVUTIL_FFVERSION_H */
