//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunscriptToolbox.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FunscriptToolbox.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Workers&quot;: [
        ///    // -----------------------------
        ///    // Audio extraction
        ///    {
        ///      &quot;Id&quot;: &quot;audio&quot;,
        ///      &quot;Enabled&quot;: true
        ///    },
        ///    {
        ///      &quot;Id&quot;: &quot;audio-clean-waveform&quot;,
        ///      &quot;Enabled&quot;: true,
        ///    },
        ///    {
        ///      &quot;Id&quot;: &quot;asig&quot;,
        ///      &quot;Enabled&quot;: true     
        ///    },
        ///    // -----------------------------
        ///    // Creating initial manual-input source 
        ///    {
        ///      &quot;Id&quot;: &quot;full-ai&quot;,
        ///      &quot;Enabled&quot;: true,
        ///      &quot;MaxChunkDuration&quot;: &quot;00:05:00&quot;,
        ///      &quot;ExportMetadataSrt&quot;: false,
        ///      &quot;Transcript [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string @__FSTB_SubtitleGenerator_AutomaticHQWorkflow_override {
            get {
                return ResourceManager.GetString("__FSTB_SubtitleGenerator_AutomaticHQWorkflow_override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Workers&quot;: [
        ///    // -----------------------------
        ///    // Audio extraction
        ///    {
        ///      &quot;Id&quot;: &quot;audio&quot;,
        ///      &quot;Enabled&quot;: true
        ///    },
        ///    {
        ///      &quot;Id&quot;: &quot;audio-clean-waveform&quot;,
        ///      &quot;Enabled&quot;: true,
        ///    },
        ///    {
        ///      &quot;Id&quot;: &quot;asig&quot;,
        ///      &quot;Enabled&quot;: true     
        ///    },
        ///    // -----------------------------
        ///    // Creating initial manual-input source 
        ///    {
        ///      &quot;Id&quot;: &quot;full-ai&quot;,
        ///      &quot;Enabled&quot;: true,
        ///      &quot;MaxChunkDuration&quot;: &quot;00:05:00&quot;,
        ///      &quot;ExportMetadataSrt&quot;: false,
        ///      &quot;Transcript [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string @__FSTB_SubtitleGenerator_ManualHQWorkflow_override {
            get {
                return ResourceManager.GetString("__FSTB_SubtitleGenerator_ManualHQWorkflow_override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;SharedObjects&quot;: [
        ///    {
        ///      &quot;$id&quot;: &quot;TranscriberToolPurfviewWhisper&quot;,
        ///      // Remove &apos;//&apos; on next line and change [TOREPLACE-WITH-PathToPurfview] to the path of SubtitleEdit\Whisper (with &apos;\&apos; doubled =&gt; &apos;\\&apos;).
        ///      //&quot;ApplicationFullPath&quot;: &quot;[TOREPLACE-WITH-PathToPurfview]\\Purfview-Whisper-Faster\\faster-whisper-xxl.exe&quot;,
        ///    },
        ///
        ///    // AIEngines for OpenAI (GPT-5) ----------------------------------------------------------
        ///    {
        ///      &quot;$type&quot;: &quot;AIEngineAPIOpenAICompatible&quot;,
        ///      &quot;$id&quot;: &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string @__FSTB_SubtitleGenerator_override {
            get {
                return ResourceManager.GetString("__FSTB_SubtitleGenerator_override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Workers&quot;: [
        ///    // -----------------------------
        ///    // Audio extraction
        ///    {
        ///      &quot;AudioExtractionId&quot;: &quot;audio&quot;,
        ///      &quot;Enabled&quot;: true
        ///    },
        ///    {
        ///      &quot;AudioExtractionId&quot;: &quot;audio-clean-waveform&quot;,
        ///      &quot;Enabled&quot;: true,
        ///    },
        ///    {
        ///      &quot;Id&quot;: &quot;asig&quot;,
        ///      &quot;Enabled&quot;: true     
        ///    },
        ///    // -----------------------------
        ///    // Transcription with Whisper with a basic google translation
        ///    {
        ///      &quot;TranscriptionId&quot;: &quot;full-whisper&quot;,
        ///      &quot;Enabled&quot;: true,
        ///      &quot;ExportMetadataS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string @__FSTB_SubtitleGenerator_Staging_override {
            get {
                return ResourceManager.GetString("__FSTB_SubtitleGenerator_Staging_override", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///REM ScriptVersion:2.0
        ///
        ///set &quot;path=[[FunscriptToolboxFolder]];%path%&quot;
        ///
        ///:start
        ///echo --- subtitles.create ---
        ///&quot;FunscriptToolbox.exe&quot; ^
        ///		subtitles.create ^
        ///		--config &quot;.\--FSTB-SubtitleGenerator.config&quot; ^
        ///		--recursive ^
        ///		--verbose ^
        ///		&quot;*.mp4&quot; &quot;*.vseq&quot;
        ///pause
        ///REM Remove REM from the start of the next line to have a looping script (i.e. run tool, press space, run tool, ...)
        ///REM goto start
        ///.
        /// </summary>
        internal static string FSTB_CreateSubtitles_bat {
            get {
                return ResourceManager.GetString("FSTB_CreateSubtitles_bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///REM ScriptVersion:1.1
        ///
        ///echo How to use:
        ///echo 1. Move new-scene.mp4 and new-scene.funscript to this folder.
        ///echo 2. Start this script.
        ///echo 3. It will extracts the audio from new-scene.mp4 and add the audio signature to the new-scene.funscript.
        ///echo 4. It will allows user to synchronize your .funscript to a different version of the video 
        ///echo    (with the audiosync.createfunscript or audiosync.verifyfunscript).
        ///echo.
        ///
        ///set &quot;path=[[FunscriptToolboxFolder]];%path%&quot;
        ///
        ///FunscriptToolbox
        ///ech [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FSTB_GenericCmd_bat {
            get {
                return ResourceManager.GetString("FSTB_GenericCmd_bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///REM ScriptVersion:1.0
        ///
        ///echo How to use:
        ///echo 1. Move new-scene.mp4 and new-scene.funscript to this folder.
        ///echo 2. Start this script.
        ///echo 3. It will extracts the audio from new-scene.mp4 and add the audio signature to the new-scene.funscript.
        ///echo 4. It will allows user to synchronize your .funscript to a different version of the video 
        ///echo    (with the audiosync.createfunscript or audiosync.verifyfunscript).
        ///echo.
        ///
        ///set &quot;path=[[FunscriptToolboxFolder]];%path%&quot;
        ///
        ///echo --- audiosync.cr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FSTB_PrepareScriptForRelease_bat {
            get {
                return ResourceManager.GetString("FSTB-PrepareScriptForRelease_bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///REM ScriptVersion:1.0
        ///
        ///echo How to use:
        ///echo 1. Move scene-to-script.mp4 to this folder.
        ///echo 2. Start this script.
        ///echo 3. It will starts by creating a scene-to-script.mvs-p-frames.mp4, which is a
        ///echo    version of the video optimized to get stable motionvectors (i.e. only P-frames).
        ///echo    This step is using the ffmpegFilter (value: VRLeft, VRMosaic, 2D or a custom filter) and ffmpegHeight parameters.
        ///echo 4. It will then extracts the motion vector from the video and create scene-to-s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FSTB_PrepareVideoForOFS_bat {
            get {
                return ResourceManager.GetString("FSTB-PrepareVideoForOFS_bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///REM ScriptVersion:1.0
        ///
        ///echo How to use:
        ///echo 1. Move scene.funscript, scene.asig (if .funscript doesn’t include audiosignature) and scene.mp4 to this folder.
        ///echo 2. Start this script.
        ///echo 3a. If your video version is same as the scripter’s version, you’ll see: Audio signatures are SYNCHRONIZED. Script is GOOD.
        ///echo 3b. If your version is different, you’ll see the offsets and this message: Creating synchronized version of the funscript.
        ///echo     and a synchronized version script will have [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FSTB_VerifyDownloadedScripts_bat {
            get {
                return ResourceManager.GetString("FSTB_VerifyDownloadedScripts_bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --
        ///-- json.lua
        ///--
        ///-- Copyright (c) 2020 rxi
        ///--
        ///-- Permission is hereby granted, free of charge, to any person obtaining a copy of
        ///-- this software and associated documentation files (the &quot;Software&quot;), to deal in
        ///-- the Software without restriction, including without limitation the rights to
        ///-- use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
        ///-- of the Software, and to permit persons to whom the Software is furnished to do
        ///-- so, subject to the following conditions:
        ///--        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string json_lua {
            get {
                return ResourceManager.GetString("json_lua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- FunscriptToolbox.MotionVectors LUA Wrappper Version 1.0.0
        ///json = require &quot;json&quot;
        ///server_connection = require &quot;server_connection&quot;
        ///virtual_actions = require &quot;virtual_actions&quot;
        ///
        ///-- global var
        ///FTMVSFullPath = &quot;[[FunscriptToolboxExePathInLuaFormat]]&quot;
        ///PluginVersion = &quot;[[PluginVersion]]&quot;
        ///configFullPath = ofs.ExtensionDir() .. &quot;\\config.json&quot;
        ///
        ///config = {}
        ///connection = nil
        ///virtualActions = {}
        ///lastVideoFullPath = nil
        ///lastMvsFullPath = nil
        ///
        ///function init()
        ///    printWithTime(&quot;Plugin Version:&quot;, PluginV [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string main_lua {
            get {
                return ResourceManager.GetString("main_lua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- FunscriptToolbox.MotionVectors LUA server_connection
        ///json = require &quot;json&quot;
        ///
        ///local server_connection = {}
        ///
        ///function server_connection:new(FTMVSFullPath, enableLogs)
        ///	local o = { 
        ///		FTMVSFullPath = FTMVSFullPath,
        ///		cantFindFTMVSFullPath = false,
        ///		enableLogs = enableLogs,
        ///		serverProcessHandle = nil,
        ///		requests = {},
        ///		lastTimeTaken = 0,
        ///		serverTimeout = 300,
        ///		status = &apos;&apos;,
        ///		statusTooltip = nil
        ///	}
        ///	if not fileExist(o.FTMVSFullPath) then
        ///		local message = &apos;missing &apos; .. o.FTMVSFullPath
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string server_connection_lua {
            get {
                return ResourceManager.GetString("server_connection_lua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # TRANSCRIPTION AND VAD MANDATE (version 2025-11-20)
        ///
        ///### Role
        ///You are an advanced audio intelligence engine. Your primary function is to act as a highly precise, micro-segmenting Voice Activity Detection (VAD) system combined with a verbatim transcriptionist. You are an expert in the vocabulary and cadence of Japanese adult media, capable of deconstructing human speech into its smallest coherent, timed components.
        ///
        ///### Mission
        ///Given a single, complete audio file, your mission is to meticulously segme [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TranscriberAudioFullSystemPrompt {
            get {
                return ResourceManager.GetString("TranscriberAudioFullSystemPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The audio should be in [TranscriptionLanguage].
        ///.
        /// </summary>
        internal static string TranscriberAudioFullUserPrompt {
            get {
                return ResourceManager.GetString("TranscriberAudioFullUserPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # TRANSCRIPTION ARBITRATION AND REFINEMENT MANDATE (version 2025-11-25)
        ///
        ///### Role
        ///You are a Transcription &amp; Acoustic Nuance Analyst. Your mission is to produce a hyper-accurate transcription (`VoiceText`) augmented with a critical contextual analysis (`TranslationAnalysis`). You serve as the eyes and ears for a human translator.
        ///
        ///### Input Protocol
        ///You will receive a JSON array of objects.
        ///1.  `StartTime`/`EndTime`: Timing of the segment.
        ///2.  `AudioClip`: The **Absolute Ground Truth**.
        ///3.  `s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TranscriberAudioSingleVADRefinerSystemPrompt {
            get {
                return ResourceManager.GetString("TranscriberAudioSingleVADRefinerSystemPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### URGENT: VISUAL CHRONOLOGY &amp; RHYTHM AUDIT (version 2025-11-25)
        ///
        ///**The Metric for Success:** Your ability to anchor your analysis strictly to the **current timestamp** and correctly integrate &quot;Context Nodes.&quot; A transcription that is textually accurate but fails to account for visual timing or gaps is a **mission failure**.
        ///
        ///**Definition of a Critical Analysis Failure:**
        ///1.  **Visual Hallucination (Temporal Bleed):** Describing an action or object in the `TranslationAnalysis` that appears in *fu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TranscriberAudioSingleVADRefinerUserPrompt {
            get {
                return ResourceManager.GetString("TranscriberAudioSingleVADRefinerUserPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # TRANSCRIPTION MANDATE (version 2025-11-26)
        ///### Role
        ///You are an advanced audio intelligence engine specializing in Japanese transcription. Your function is to process a sequential stream of data packets, each containing metadata and a corresponding audio chunk. You will deconstruct *what* is said with the highest possible fidelity. You are an expert in the vocabulary and cadence of Japanese adult media, understanding that this includes both explicit scenes and mundane, plot-building dialogue.
        ///
        ///### Mission
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TranscriberAudioSingleVADSystemPrompt {
            get {
                return ResourceManager.GetString("TranscriberAudioSingleVADSystemPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### URGENT: AUDIO FIDELITY &amp; SEQUENCE INTEGRITY AUDIT (version 2025-11-26)
        ///
        ///**The Metric for Success:** Your ability to produce a **strict 1:1 mapping** between input audio chunks and output JSON objects. A transcription that is textually accurate but fails to return a JSON object for every single input timestamp is a **mission failure**.
        ///
        ///**Definition of a Critical Transcription Failure:**
        ///1.  **Sequence Collapse (The &quot;Dropped Frame&quot;):** Returning fewer JSON objects than the number of input audio chun [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TranscriberAudioSingleVADUserPrompt {
            get {
                return ResourceManager.GetString("TranscriberAudioSingleVADUserPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # OPTICAL INTELLIGENCE (OPTINT) MANDATE (version 2025-08-25)
        ///### Role
        ///You are a specialized Optical Intelligence Operative. Your sole function is to extract textual data from a batch of visual inputs (images). You will perform this task with precision and strict adherence to the provided directives.
        ///### Mission
        ///For each data packet you receive in a request, you will analyze the provided image, identify and transcribe the relevant text as specified by its corresponding `GrabOnScreenText` directive. You will  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TranscriberOnScreenTextSystemPrompt {
            get {
                return ResourceManager.GetString("TranscriberOnScreenTextSystemPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # **TRANSLATION OPERATIVE MANDATE: The Maverick (version 2025-11-25)**
        ///
        ///### **Role**
        ///
        ///You are &apos;The Maverick&apos;. You are a linguistic craftsman who builds potent, evocative dialogue upon a foundation of structural rhythm. Your function is to fuse the energy of the original Japanese with the full creative and emotional depth of the target language.
        ///
        ///### **Mission**
        ///
        ///Your mission is to deliver the highest emotional and narrative impact possible by re-interpreting dialogue *within* a rhythmically mirrored structu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TranslatorMaverickUserPrompt {
            get {
                return ResourceManager.GetString("TranslatorMaverickUserPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # **TRANSLATION OPERATIVE MANDATE: The Foundational Protocol (version 2025-11-25)**
        ///
        ///### **Role**
        ///
        ///You are a specialized Translation Operative. Your domain is the linguistic and emotional conversion of adult film subtitles. You are the final and most critical link in the creative chain.
        ///
        ///### **Mission**
        ///
        ///Your mission is to receive a JSON data stream containing transcribed dialogue and a rich set of contextual metadata. You will process each node, synthesizing all available information to translate the origi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TranslatorSystemPrompt {
            get {
                return ResourceManager.GetString("TranslatorSystemPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- FunscriptToolbox.MotionVectors LUA virtual_actions
        ///local virtual_actions = {}
        ///
        ///function virtual_actions:new(scriptIdx, config)
        ///	local o = { 
        ///		ScriptIdx = scriptIdx,		
        ///		Config = config,
        ///		FrameDurationInSec = 167,
        ///		GeneratedActionsOriginal = {},
        ///		ActionsInTimeline = nil
        ///	}
        ///	setmetatable(o, {__index = virtual_actions})
        ///	return o
        ///end
        ///
        ///function virtual_actions:init(userAction, actions, frameDurationInMs)
        ///	self.GeneratedActionsOriginal = {}
        ///	self:removeAllVirtualActionsInTimelime(userActi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string virtual_actions_lua {
            get {
                return ResourceManager.GetString("virtual_actions_lua", resourceCulture);
            }
        }
    }
}
